server:
 port: 8082
 
 servlet:
  context-path: /api/v1
 
spring:
 application: 
  name: EMS-Queries
  
 datasource:
  url: jdbc:mysql://localhost:3306/employeedb
  username: root
  password: password
  driver-class-name: com.mysql.cj.jdbc.Driver
  
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update 
   
 kafka: 
  template:
   default-topic: employee-topic
  consumer:
   bootstrap-servers: localhost:9092
   group-id: employee-group1
   auto-offset-reset: earliest
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
   
   properties:
    spring:
     json:
      trusted:
       packages: net.miaoubich.event