services:
 zookeeper:
  image: confluentinc/cp-zookeeper:latest
  container_name: my-zookeeper
  environment:
   ZOOKEEPER_SERVER_ID: 1
   ZOOKEEPER_CLIENT_PORT: 2181
   ZOOKEEPER_TICK_TIME: 2000
  ports:
   - "2181:2181"
  networks:
   - my-network
 
 kafka:
  image: confluentinc/cp-kafka:latest
  container_name: my-kafka
  ports:
   - "9092:9092"
  depends_on:
   - zookeeper
  environment:
   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
   KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
   KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  networks:
   - my-network
   
networks:
 my-network:
  driver: bridge  
  
 